name: ML CI/CD - Train, Register, Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write # required for OIDC
  contents: read

jobs:
  ml-cicd:
    runs-on: ubuntu-latest
    environment: main
    env:
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
      AZURE_WORKSPACE_NAME: ${{ vars.AZURE_WORKSPACE_NAME }}
      AML_COMPUTE: ${{ vars.AML_COMPUTE }}
      AML_ENDPOINT_NAME: ${{ vars.AML_ENDPOINT_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Azure CLI ML extension and libs
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-ml pandas scikit-learn joblib pytest
          az extension add -n ml --yes

        # (Optional) Run unit tests
      - name: Run unit tests
        run: pytest -q

      # TRAIN WAIT REGISTER DEPLOY

      # Submit the training job and WAIT until it finishes
      - name: Submit AML training job and wait
        run: |
          az ml compute list \
            --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
            --workspace-name "${{ vars.AZURE_WORKSPACE_NAME }}" -o table

          JOB_ID=$(az ml job create \
            --file ml/pipeline-job.yaml \
            --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
            --workspace-name "${{ vars.AZURE_WORKSPACE_NAME }}" \
            --set compute=azureml:${AML_COMPUTE} \
            --query name -o tsv)

          echo "Submitted job: $JOB_ID"
          echo "JOB_ID=$JOB_ID" >> "$GITHUB_ENV"

          az ml job stream --name "$JOB_ID" \
            --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
            --workspace-name "${{ vars.AZURE_WORKSPACE_NAME }}"

      # Inspect the job's outputs and register the model
      - name: Inspect job outputs (temporary)
        run: |
          az ml job download --name "$JOB_ID" \
            --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
            --workspace-name "${{ vars.AZURE_WORKSPACE_NAME }}" \
            --download-path ./_job --all
          echo "Downloaded files:"
          ls -R ./_job

      # Register the model from the job's outputs
      - name: Register model (take last job's outputs)
        run: |
          echo "Using job: $JOB_ID"
          # Try the artifacts path (works even if you didn't declare named outputs)
          az ml model create \
            --name iris-model \
            --type custom_model \
            --path "azureml://jobs/${JOB_ID}/outputs/artifacts/paths/outputs/model.joblib" \
            --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
            --workspace-name "${{ vars.AZURE_WORKSPACE_NAME }}"

      # Create the endpoint if it doesn't exist (idempotent)
      - name: Create endpoint (idempotent)
        run: |
          az ml online-endpoint show \
            --name "${{ vars.AML_ENDPOINT_NAME }}" \
            --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
            --workspace-name "${{ vars.AZURE_WORKSPACE_NAME }}" \
            || az ml online-endpoint create \
                 --name "${{ vars.AML_ENDPOINT_NAME }}" \
                 --file infra/endpoint.yaml \
                 --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
                 --workspace-name "${{ vars.AZURE_WORKSPACE_NAME }}"

      # Create/Update the deployment and route 100% traffic
      - name: Create/Update deployment
        run: |
          MODEL_VER=$(az ml model list --name iris-model \
            --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
            --workspace-name "${{ vars.AZURE_WORKSPACE_NAME }}" \
            --query "[-1].version" -o tsv)

          echo "Latest model version: $MODEL_VER"

          # Update the YAML to point at the latest version
          sed -i "s#azureml:iris-model:1#azureml:iris-model:${MODEL_VER}#g" infra/deployment.yaml

          az ml online-deployment create \
            --file infra/deployment.yaml \
            --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
            --workspace-name "${{ vars.AZURE_WORKSPACE_NAME }}" \
            --all-traffic

      # (Optional) Smoke test: invoke the endpoint once
      - name: Invoke endpoint (smoke test)
        run: |
          az ml online-endpoint invoke \
            --name "${{ vars.AML_ENDPOINT_NAME }}" \
            --request-file request.json \
            --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
            --workspace-name "${{ vars.AZURE_WORKSPACE_NAME }}"
